mainblog/urls.py
from django.urls import include, path

from . import views

app_name = "mainblog"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

matkulList/urls.py
from django.urls import  path

from . import views

app_name = 'matkulList'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('view/<int:id>', views.view, name="view"),
    path('delete/<int:id>', views.remove, name="delete")
]

ppwstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('oldprofile.urls')),
    path('matkul/', include('matkulList.urls')),
    path('event/', include('eventList.urls')),
    path('dasdisbook/', include('dasdisBook.urls')),
    path('bulletin/', include('bulletinBoard.urls')),
    path('', include('mainblog.urls'))
]

matkulList/models.py
import re
from django.utils.translation import gettext_lazy as _

from django import forms
from django.db import models

termpattern = re.compile(r"^\b(Gasal|Genap) \d{4}\/\d{4}$")

class MatKul(models.Model):
    title = models.CharField(max_length=100)
    term = models.CharField(max_length=15)
    lecturer = models.CharField(max_length=100)
    total_credits = models.IntegerField()
    location = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title



class MatKulForm(forms.ModelForm):
    class Meta:
        model = MatKul
        fields = ['title', 'term', 'lecturer', 'total_credits', 'location', 'description']
        labels = {
            'total_credits' : _('Total credits')
        }

    def clean(self):
        super(MatKulForm, self).clean()

        term = self.cleaned_data.get('term')

        if (not term):
            self._errors['term'] = self.error_class(
                ['This form must be filled!']
            )
        elif (not termpattern.match(term)):
            self._errors['term'] = self.error_class(
                ['Incorrect term format! (Should be "Gasal 2019/2020" or "Genap 2019/2020" in any year)']
            )

        return self.cleaned_data
        

matkulList/views.py
from .models import MatKul, MatKulForm
from django.contrib.messages import get_messages, success, error
from django.shortcuts import get_object_or_404, redirect, render, reverse

def index(request):
    messages = get_messages(request)
    matkulList = MatKul.objects.all()
    return render(request, 'matkulList/index.html', {'matkulList' : matkulList, "messages" : messages})

def view(request, id):
    matkul = MatKul.objects.filter(pk=id).first()
    if (matkul == None):
        error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("matkulList:index"))
    return render(request, 'matkulList/view.html', {'matkul' : matkul})

def add(request):
    if (request.method == "POST"):
        form = MatKulForm(request.POST)
        if (form.is_valid()):
            matkul = MatKulForm.save(form)
            success(request, "Matkul telah ditambahkan!")
            return redirect(reverse('matkulList:index'))
        else:
            return render(request, 'matkulList/add.html', {'form' : form})
    else:
        form = MatKulForm()
    
    return render(request, 'matkulList/add.html', {'form' : form})

def remove(request, id):
    matkul = MatKul.objects.filter(pk=id).first()
    if (matkul == None):
        error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("matkulList:index"))
    if (request.method == "POST"):
        MatKul.delete(matkul)
        success(request, "Matkul telah dihapus!")
        return redirect(reverse("matkulList:index"))
    else:
        return render(request, 'matkulList/remove.html', {'matkul' : matkul})

templates/matkulList/add.html
{% extends "matkulList/base.html" %}

{% block addition %}- Add Matkul{% endblock %}

{% load static %}
{% load bootstrap4 %}
{% block matkulstuff %}
<h2>Add Matkul</h2>
<form action="{% url 'matkulList:add' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn ppwstories-btn" type="submit" value="add">
</form>
{% endblock %}

templates/matkulList/base.html
{% extends "mainblog/base.html" %}

{% block title %}MatkulList {% block addition %}{% endblock %}{% endblock %}

{% block content %}
<h1>Matkul List</h1>
{% block matkulstuff %}
{% endblock %}
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}

templates/matkulList/index.html
{% extends "matkulList/base.html" %}

{% block addition %}{% endblock %}

{% load static %}
{% block matkulstuff %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}class="alert alert-danger"
    {% else %} class="alert alert-success" {% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'matkulList:add' %}" class="btn ppwstories-btn" style="margin: 10px;">add</a>
<ul>
    {% for matkul in matkulList %}
    <li>
        <div class="postpreview">
            <div class="textbox">
                <h2><a href="{% url 'matkulList:view' matkul.pk %}">{{ matkul.title }}</a></h2>
                <p>
                    {{ matkul.term }}<br>
                    Lecturer: {{ matkul.lecturer }}<br>
                    Total credits: {{ matkul.total_credits }} credits<br>
                    Location: {{ matkul.location }}
                </p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/matkulList/remove.html
{% extends "matkulList/base.html" %}

{% block addition %}{% endblock %}

{% load static %}
{% block matkulstuff %}
<h2>Delete Matkul</h2>
<p>Are you sure you want to delete <b>{{ matkul.title }}</b>?</p>
<form action="" method="POST">
    {% csrf_token %}
    <div style="display: block-inline;">
        <input class="btn ppwstories-btn" type="submit" value="Delete">
        <a class="btn ppwstories-btn" href="{% url 'matkulList:view' matkul.pk %}">Go back</a>
    </div>
</form>
{% endblock %}

templates/matkulList/view.html
{% extends "matkulList/base.html" %}

{% block addition %}- {{ matkul.title }}{% endblock %}

{% load static %}
{% block matkulstuff %}
<h2>{{ matkul.title }}</h2>
<p><b>{{ matkul.term }}</b></p>
<p><b>Lecturer:</b> {{ matkul.lecturer }}</p>
<p><b>Total credits:</b> {{ matkul.total_credits }} credits</p>
<p><b>Location:</b> {{ matkul.location }}</p>
<P><b>Description:</b><br>{{matkul.description }}</P>
<div style="display: inline-block;">
    <a class="btn ppwstories-btn" href="{% url 'matkulList:delete' matkul.pk %}">Delete</a>
    <a class="btn ppwstories-btn" href="{% url 'matkulList:index' %}">Back</a>
</div>
{% endblock %}