bulletinBoard/urls.py
from django.urls import  path

from . import views

app_name = 'bulletinBoard'

urlpatterns = [
    path('', views.index, name="index"),
    path('post/', views.post, name="post"),
    path('view', views.view, name="view"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signUp_view, name="signup")
]

mainblog/urls.py
from django.urls import include, path

from . import views

app_name = "mainblog"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

ppwstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('oldprofile.urls')),
    path('matkul/', include('matkulList.urls')),
    path('event/', include('eventList.urls')),
    path('dasdisbook/', include('dasdisBook.urls')),
    path('bulletin/', include('bulletinBoard.urls')),
    path('', include('mainblog.urls'))
]

bulletinBoard/models.py
from django.contrib.auth.models import User
from django import forms
from django.db import models

class BulletinPost(models.Model):
    content = models.TextField(max_length=2000)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    postTime = models.DateTimeField(auto_now_add=True)

class BulletinPostForm(forms.ModelForm):
    class Meta:
        model = BulletinPost
        fields = ['content']

bulletinBoard/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.shortcuts import redirect, render, reverse
from django.utils.html import escape

from .models import BulletinPost, BulletinPostForm

def index(request):
    form = BulletinPostForm()
    return render(request, 'bulletinBoard/index.html', {'form' : form})

def view(request):
    page = request.GET.get('p')
    if (page == None):
        return redirect(reverse('bulletinBoard:view')+"?p=1")
    page = int(page)
    bulletinpost = BulletinPost.objects.order_by("-postTime")
    if (len(bulletinpost) < (page-1)*10):
        page = len(bulletinpost) // 10 + 1
        return redirect(reverse('bulletinBoard:view')+"?p="+str(page))
    bulletinpost = bulletinpost[(page-1)*10:page*10]
    result = dict()
    i = 0
    for a in bulletinpost:
        post = {
            "content" : escape(a.content),
            "username" : a.user.username,
            "postTime" : str(a.postTime)
        }
        result[i] = post
        i += 1
    return JsonResponse(result)

def post(request):
    if (not request.user.is_authenticated):
        return HttpResponseForbidden()
    if (request.method == "GET"):
        return HttpResponseForbidden()
    form = BulletinPostForm(request.POST or None)
    if (not form.is_valid()):
        return HttpResponseBadRequest()
    else:
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return JsonResponse({'status' : 'success'})


def login_view(request):
    if (request.user.is_authenticated):
        return redirect(reverse('bulletinBoard:index'))
    elif (request.method == "POST"):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if (user is not None):
            login(request, user)
            return redirect(reverse('bulletinBoard:index'))
        else:
            return render(request, 'bulletinBoard/login.html', { "error" : "Your username or password is incorrect."})
    else: 
        return render(request, 'bulletinBoard/login.html')

def logout_view(request):
    logout(request)
    return redirect(reverse('bulletinBoard:index'))

def signUp_view(request):
    if (request.user.is_authenticated):
        return redirect(reverse('bulletinBoard:index'))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('bulletinBoard:index'))
    else:
        form = UserCreationForm()
    return render(request, 'bulletinBoard/signup.html', {'form': form})

templates/bulletinBoard/base.html
{% extends "mainblog/base.html" %}

{% block title %}Bulletin Board {% block addition %}{% endblock %}{% endblock %}

{% block content %}
<h1>Bulletin Board</h1>
{% block bulletinBoard %}
{% endblock %}
{% endblock %}

templates/bulletinBoard/index.html
{% extends "bulletinBoard/base.html" %}

{% block addtion %}| login{% endblock %}

{% block bulletinBoard %}
<h2>See what have been posted here!</h2>
<div class="d-flex justify-content-between">
    <div>
        {% if user.is_authenticated %}
        You logged in as <b>{{ request.user.username }}</b> <a class="btn ppwstories-btn" href="{% url 'bulletinBoard:logout' %}">logout</a>
        {% else %}
        Login or sign up to post in Bulletin Board
        {% endif %}
    </div>
    <div role="group" aria-label="Basic example">
        <a class="btn ppwstories-btn" href="{% url 'bulletinBoard:login' %}">Login</a>
        <a class="btn ppwstories-btn" href="{% url 'bulletinBoard:signup' %}">Sign Up</a>
    </div>
</div>
<div class="d-flex" style="min-height: 200px; min-width: 100%;">
    <ul class="list-group" id="BulletinPosts">
    </ul>
</div>
<script>
function loadPosts() {
    $.ajax({
        url: "{% url 'bulletinBoard:view' %}?p=1",
        type: "GET",
        dataType: "json",
        success: function(result) {
            resultHTML = "";
            $.each(result, function(key, val) {
                resultHTML += "<li class='list-group-item'>";
                resultHTML += "<b>" + val.username + "</b> at " + val.postTime + "<br>";
                resultHTML += "<p>" + val.content + "</p>";
                resultHTML += "</li>";
            });
            $("#BulletinPosts").html(resultHTML);
        }
    })
}

$(document).ready(loadPosts);
</script>
{% if user.is_authenticated %}
<script>
function post(){
    $("#fail").css("display","none")
    var content = $("#id_content").val();
    if (content.length > 0) {
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            url: "{% url 'bulletinBoard:post' %}",
            type: "POST",
            data: {'content' : content},
            success: loadPosts,
            error: function(){$("#fail").css("display","block")}
        });
    }
}
</script>
<h2>Post something here!</h2>
<div class="alert alert-danger" role="alert" id="fail" style="display: none;">
    Whoops! There is something wrong from here! O.o
</div>
<div id="bulletinForm">
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <button class="btn ppwstories-btn" onclick="post()">Post</button>
</form>
{% endif %}
{% endblock %}

templates/bulletinBoard/login.html
{% extends "bulletinBoard/base.html" %}

{% block addtion %}| login{% endblock %}

{% block bulletinBoard %}
<h2>Login</h2>
<div class="form-group">
    Login to post in Bulletin Board
</div>
{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" name="username" placeholder="Username" required>
    </div>
    <div class="form-group">
        <label for="password">Password: </label>
        <input type="password" class="form-control" name="password" placeholder="Password" required>
    </div>
    <button type="submit" class="btn ppwstories-btn">Login</button>
</form>
<div class="form-group">
    <p>Haven't created one? <a class="btn ppwstories-btn" href="{% url 'bulletinBoard:signup' %}">Sign Up</a></p>
</div>
{% endblock %}

templates/bulletinBoard/signup.html
{% extends "bulletinBoard/base.html" %}

{% block addtion %}| Sign Up{% endblock %}

{% block bulletinBoard %}
<h2>Daftar</h2>
<form method="post">
    {% csrf_token %}
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <button type="submit" class="btn ppwstories-btn">Daftar</button>
</form>
<div class="form-group">
    Already have an account <a class="btn ppwstories-btn" href="{% url 'bulletinBoard:login' %}">Login</a>
</div>
{% endblock %}