mainblog/urls.py
from django.urls import include, path

from . import views

app_name = "mainblog"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

oldprofile/urls.py
from django.urls import include, path

from . import views

app_name = "oldprofile"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.viewProfile, name="profile")
]

ppwstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('oldprofile.urls')),
    path('matkul/', include('matkulList.urls')),
    path('event/', include('eventList.urls')),
    path('dasdisbook/', include('dasdisBook.urls')),
    path('bulletin/', include('bulletinBoard.urls')),
    path('', include('mainblog.urls'))
]

oldprofile/models.py
from django.db import models

# Create your models here.

oldprofile/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'oldprofile/index.html')

def viewProfile(request):
    return render(request, 'oldprofile/profile.html')

templates/oldprofile/base.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>PPW Story 1 | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'oldprofile/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
        <div class="navbar">
            <ul>
                <li><a href="{% url 'oldprofile:index' %}">PPW Story 1</a></li>
                <li><a href="{% url 'mainblog:index' %}">William's PPW Stories</a></li>
            </ul>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <div class="footer">
            <p>Created in 2020 by William</p>
        </div>
{% endblock %}

templates/oldprofile/index.html
{% extends 'oldprofile/base.html' %}
{% load static %}
{% block title %} Selamat Datang! {% endblock %}
{% block content %}
    <h2>Selamat Datang!</h2>
    <p>Selamat datang di web pertama saya!</p>
    <img alt="ProfilePic" src="{% static 'oldprofile/profilepic.jpg' %}">
    <h2>William</h2>
    <p>Gemar mempelajari hal-hal baru</p>
    <div class="button">
        <a href="{% url 'oldprofile:profile' %}">Tampilkan</a>
    </div>
{% endblock %}

templates/oldprofile/profile.html
{% extends 'oldprofile/base.html' %}
{% load static %}
{% block title %}Profile Saya{% endblock %}
{% block content %}
    <h2>Profile Saya</h2>
    <img alt="ProfilePic" src="{% static 'oldprofile/profilepic.jpg' %}">
    <table>
        <tr>
            <td>Nama</td>
            <td>William</td>
        </tr> 
        <tr>
            <td>NPM</td>
            <td>1906350521</td>
        </tr>
        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>
    </table>
    <h2>Hobi</h2>
    <p>Main game, Belajar hal baru</p>
    <h2>Deskripsi</h2>
    <p>
        Aku suka belajar hal-hal baru, namun aku cepat bosan. Sebelum kuliah, aku sudah belajar pemrograman,
        tapi sepertinya aku perlu belajar lebih banyak lagi.
    </p>
    <h2>Riwayat pendidikan</h2>
    <ul>
        <li>
            <p>S1 Ilmu Komputer, Universitas Indonesia (2019 - sekarang)</p>
        </li>
        <li>
            <p>SMA Negeri 2 Jakarta (2016 - 2019)</p>
        </li>
        <li>
            <p>SMP Kristen 2 BPK Penabur (2016 - 2013)</p>
        </li>
    </ul>
    <h2>
        Kontak
    </h2>
    <div class="contact">
        <a href="https://twitter.com/hori_75">
            <img alt="twitter" src="{% static 'oldprofile/twitter.png' %}">
        </a>
        <a href="https://www.linkedin.com/in/william-8611851a0/">
            <img alt="linkedin" src="{% static 'oldprofile/linkedin.png' %}" style="max-width: 59px; max-height: 59px;">
        </a>
    </div>
{% endblock %}