dasdisBook/urls.py
from django.urls import path

from . import views

app_name = "dasdisBook"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search")
]

eventList/urls.py
from django.urls import path

from . import views

app_name = "eventList"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("join/<int:id>", views.join, name="join")
]

mainblog/urls.py
from django.urls import include, path

from . import views

app_name = "mainblog"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

matkulList/urls.py
from django.urls import  path

from . import views

app_name = 'matkulList'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('view/<int:id>', views.view, name="view"),
    path('delete/<int:id>', views.remove, name="delete")
]

oldprofile/urls.py
from django.urls import include, path

from . import views

app_name = "oldprofile"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.viewProfile, name="profile")
]

ppwstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('oldprofile.urls')),
    path('matkul/', include('matkulList.urls')),
    path('event/', include('eventList.urls')),
    path('dasdisbook/', include('dasdisBook.urls')),
    path('bulletin/', include('bulletinBoard.urls')),
    path('', include('mainblog.urls'))
]

mainblog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    mini_thumbnail = models.CharField(max_length=100)
    thumbnail = models.CharField(max_length=100)
    summary = models.TextField(max_length=250)
    content = models.TextField(max_length=4000)

    def __str__(self):
        return self.title

mainblog/views.py
from django.http import Http404
from django.shortcuts import redirect, render, reverse, get_object_or_404
from django.template import TemplateDoesNotExist

from .models import Post

def index(request):
    allPosts = Post.objects.all()
    return render(request, 'mainblog/index.html', {'allPosts': allPosts})

def profile(request):
    return render(request, 'mainblog/profile.html')

def posts(request, number=0):
    if (number==0):
        return redirect(reverse('mainblog:index'))
    else:
        post = get_object_or_404(Post, pk=number)
        return render(request, 'mainblog/post.html', {'post' : post})

templates/mainblog/base.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
    <title>William's PPW Stories | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'mainblog/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'mainblog/js/collapse.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 sidebar">
                <img alt="William's photo" src="{% static 'mainblog/img/William.png' %}">
                <h2>William</h2>
                {% block sidebar %}
                {% endblock %}
                <div class="listgroup" style="max-width: 200px; margin: auto;">
                    <a class="list-group-item ppwstories-btn" href="{% url 'mainblog:index' %}">Main Page</a>
                    <a class="list-group-item ppwstories-btn" href="{% url 'mainblog:profile' %}">View Profile</a>
                    <a class="list-group-item ppwstories-btn" href="{% url 'oldprofile:index' %}">PPW Story 1</a>
                    <a class="list-group-item ppwstories-btn" href="{% url 'matkulList:index' %}">Matkul List</a>
                    <a class="list-group-item ppwstories-btn" href="{% url 'eventList:index' %}">Event List</a>
                    <a class="list-group-item ppwstories-btn" href="{% url 'dasdisBook:index' %}">DasdisBook</a>
                </div>
            </div>
            <div class="col-md-9 col-md-offset-3 content">
                <div class="content container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/mainblog/index.html
{% extends "mainblog/base.html" %}

{% block title %}Summary{% endblock %}

{% load static %}
{% block content %}
<h1>See What I have worked on...</h1>
<ul>
    {% for post in allPosts %}
    <li>
        <div class="postpreview">
            <img alt="minithubnail" src="{% static post.mini_thumbnail %}">
            <div class="textbox">
                <h2><a href="{% url 'mainblog:posts' post.pk %}">{{ post.title }}</a></h2>
                <p>{{ post.summary }}</p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}

templates/mainblog/post.html
{% extends "mainblog/base.html" %}

{% load static %}
{% block content %}
<h1>{{ post.title }}</h1>
<div class="post">
    <img alt="thumbnail" src="{% static post.thumbnail %}">
    <div class="maintext">
        {{ post.content|safe }}
    </div>
</div>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}

templates/mainblog/profile.html
{% extends "mainblog/base.html" %}

{% block title %}William's Profile{% endblock %}
{% load static %}
{% block content %}
<h1>My Profile</h1>
<div class="accordion" id="profileAccordion">
    <div class="card">
        <div class="card-header pb-0" id="headingOne">
            <h2 class="mb-0">
                <button class="btn collapsible" type="button" data-toggle="collapse" data-target="#collapseDescription">
                    Description
                </button>
                <ul style="float: right;">
                    <li style="float: right;"><button class="btn down"></button></li>
                    <li style="float: right;"><button class="btn up"></button></li>
                </ul>
            </h2>
        </div>

        <div id="collapseDescription" class="collapse show" data-parent="#profileAccordion">
            <div class="card-body">
                I love to learn new things, but sometimes I got bored and move on to other things. Learned programming earlier in high school, but I still have much to learn.
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header pb-0" id="headingTwo">
            <h2 class="mb-0">
                <button class="btn collapsible" type="button" data-toggle="collapse" data-target="#collapseExperience">
                    Experience
                </button>
                <ul style="float: right;">
                    <li style="float: right;"><button class="btn down"></button></li>
                    <li style="float: right;"><button class="btn up"></button></li>
                </ul>
            </h2>
        </div>

        <div id="collapseExperience" class="collapse show" data-parent="#profileAccordion">
            <div class="card-body">
                <ul style="list-style-type: circle; margin-left: 25px;">
                    <li>
                        <b>Teaching Assistant of Introduction to Digital Systems</b><br>
                        <p>September 2020 - Present<br>
                        I help creating tasks and assist students in Introduction to Digital Systems.</p>
                    </li>
                    <li>
                        <b>Junior Member of Network Security and Operating System (NetSOS) SIG in RISTEK, Faculty of Computer Science, Universitas Indonesia</b>
                        <p>March 2019 - Present<br>
                        In this group, I learned web and app security and test my skills in Capture The Flag competitions.</p>
                    </li>
                    <li>
                        <b>Staff of Capture The Flag Competition in COMPFEST 2020</b>
                        <p>March 2019 - October 2020<br>
                        I'm assigned to a group whose job was to design challenges for HackerClass, Elimination round, and Final round in jeopardy format.</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header pb-0" id="headingThree">
            <h2 class="mb-0">
                <button class="btn collapsible" type="button" data-toggle="collapse" data-target="#collapseAchievements">
                    Achievements
                </button>
                <ul style="float: right;">
                    <li style="float: right;"><button class="btn down"></button></li>
                    <li style="float: right;"><button class="btn up"></button></li>
                </ul>
            </h2>
        </div>

        <div id="collapseAchievements" class="collapse show" data-parent="#profileAccordion">
            <div class="card-body">
                <ul style="list-style-type: circle; margin-left: 25px;">
                    <li>
                        <b>2nd Place in CTF Pekan RISTEK 2019</b>
                        <p>This is an introductory Capture The Flag by RISTEK where we solve basic and easy challenges</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header pb-0" id="headingFour">
            <h2 class="mb-0">
                <button class="btn collapsible" data-toggle="collapse" data-target="#collapseSkills">
                    Skills
                </button>
                <ul style="float: right;">
                    <li style="float: right;"><button class="btn down"></button></li>
                    <li style="float: right;"><button class="btn up"></button></li>
                </ul>
            </h2>
        </div>

        <div id="collapseSkills" class="collapse show" data-parent="#profileAccordion">
            <div class="card-body">
                <ul style="list-style-type: circle; margin-left: 25px;">
                    <li>
                        <b>Basic Programming (Java, Python, C++)</b>
                        <p>I have learned Java and Python since I'm entering University. Now, I'm learning to create and use effective algorithms.</p>
                    </li>
                    <li>
                        <b>Basic Web Programming (Django)</b>
                        <p>I could create basic web application. I usually create the application using Django.</p>
                    </li>
                </ul>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header pb-0" id="headingFive">
                <h2 class="mb-0">
                    <button class="btn collapsible" type="button" data-toggle="collapse" data-target="#collapseActivity">
                        What am I doing here?
                    </button>
                    <ul style="float: right;">
                        <li style="float: right;"><button class="btn down"></button></li>
                        <li style="float: right;"><button class="btn up"></button></li>
                    </ul>
                </h2>
            </div>
    
            <div id="collapseActivity" class="collapse show" data-parent="#profileAccordion">
                <div class="card-body">
                    What am I doing here? Learning web development, of course! :)
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block sidebar %}
<h2>Contact</h2>
<p>Email: william92@ui.ac.id</p>
<h2>Social Media</h2>
<div style="display: inline-block; margin-bottom: 20px;">
    <a href="https://twitter.com/hori_75" ><img src="{% static 'mainblog/img/twitter.png' %}" alt="twitter" style="width: 50px; height: 50px;"></a>
    <a href="https://www.linkedin.com/in/william-8611851a0/"><img src="{% static 'oldprofile/linkedin.png' %}" alt="Linkedin" style="max-width: 59px; max-height: 59px;"></a>
</div>
{% endblock %}